### ISSUE TITLE
ReferenceError: CodeMap is not defined

### ISSUE THREAD

**Issue by SiAdcock** [notonthehighstreet/breadboard#10]
The following error occurs when running the kitchen example in node v4.4.2

> breadboard:error ReferenceError: CodeMap is not defined
    at v8/tools/profile.js:558:44
    at NativeModule.compile (node.js:959:5)
    at Function.NativeModule.require (node.js:904:18)
    at Function.Module._load (module.js:285:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.substitutes.some.Object.defineProperty.get [as v8/tools/profile] (/Users/simonadcock/workspace/breadboard/lib/getNativeModules.js:20:20)
    at Function.assign (native)
    at /Users/simonadcock/workspace/breadboard/lib/createInjector.js:21:12
    at process._tickCallback (node.js:369:9) +2ms

It is not limited to the kitchen example, it also occurs in another project for which we are using Breadboard.

This does not happen in node v4.3.2

**Comment by kosmotaur** [comment]
[`createInjector.js:21:12`](https://github.com/notonthehighstreet/breadboard/blob/master/lib/createInjector.js#L21) - points to extending the `deps` with native, explicit and app dependencies.

Interestingly, this seems to be calling the getter, which we don't want to happen any sooner then within the applications lifecycle! Otherwise we lose the lazy-loading aspect. I guess we need to somehow, cunningly, create the getter functions in the very last step of building `deps`. Values of the sub-objects which make up `deps` could be just paths to modules initially. After chucking them all into `deps`, or an intermediate object, we could map values to be getter functions `require`ing the path only when a Breadboard module function is actually executed. Should create a ticket for that.

As to the error itself, is it possible that when going through native dependencies, we require something that is not supposed to be required in context of running a Breadboard app? Like the Profiler?
